
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "AREA ELEMENTO LINGUA NOTA NUMERO SIN TEXTO TIPO VAR VIDelementos : elementos elemento\n                 | elementos vids\n                 | \n                 elemento : ELEMENTO NUMERO texto tipo areatipo : TIPO texto\n            |\n    area : AREA texto sin\n            | AREA texto var\n            | AREA texto lingua\n    lingua :  LINGUA texto lingua\n                | LINGUA texto nota\n                | LINGUA texto vids\n                | LINGUA texto\n    sin : SIN texto lingua\n           | SIN texto var\n    vids : vid\n    vid : VID texto '»' texto\n            | VID texto '»' texto vid\n    var : VAR texto linguanota : NOTA texto vids\n            | NOTA texto\n    texto : TEXTO texto\n            | NUMERO texto\n            | TEXTO"
    
_lr_action_items = {'ELEMENTO':([0,1,2,3,5,9,13,14,17,18,21,23,24,25,31,32,33,34,35,36,37,39,40,],[-3,4,-1,-2,-16,-24,-22,-23,-17,-4,-18,-7,-8,-9,-13,-14,-15,-19,-10,-11,-12,-21,-20,]),'VID':([0,1,2,3,5,9,13,14,17,18,21,23,24,25,31,32,33,34,35,36,37,39,40,],[-3,6,-1,-2,-16,-24,-22,-23,6,-4,-18,-7,-8,-9,6,-14,-15,-19,-10,-11,-12,6,-20,]),'$end':([0,1,2,3,5,9,13,14,17,18,21,23,24,25,31,32,33,34,35,36,37,39,40,],[-3,0,-1,-2,-16,-24,-22,-23,-17,-4,-18,-7,-8,-9,-13,-14,-15,-19,-10,-11,-12,-21,-20,]),'NUMERO':([4,6,7,9,10,12,16,19,26,27,28,38,],[7,10,10,10,10,10,10,10,10,10,10,10,]),'TEXTO':([6,7,9,10,12,16,19,26,27,28,38,],[9,9,9,9,9,9,9,9,9,9,9,]),'»':([8,9,13,14,],[12,-24,-22,-23,]),'TIPO':([9,11,13,14,],[-24,16,-22,-23,]),'AREA':([9,11,13,14,15,20,],[-24,-6,-22,-23,19,-5,]),'SIN':([9,13,14,22,],[-24,-22,-23,26,]),'VAR':([9,13,14,22,29,],[-24,-22,-23,27,27,]),'LINGUA':([9,13,14,22,29,30,31,],[-24,-22,-23,28,28,28,28,]),'NOTA':([9,13,14,31,],[-24,-22,-23,38,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'elementos':([0,],[1,]),'elemento':([1,],[2,]),'vids':([1,31,39,],[3,37,40,]),'vid':([1,17,31,39,],[5,21,5,5,]),'texto':([6,7,9,10,12,16,19,26,27,28,38,],[8,11,13,14,17,20,22,29,30,31,39,]),'tipo':([11,],[15,]),'area':([15,],[18,]),'sin':([22,],[23,]),'var':([22,29,],[24,33,]),'lingua':([22,29,30,31,],[25,32,34,35,]),'nota':([31,],[36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> elementos","S'",1,None,None,None),
  ('elementos -> elementos elemento','elementos',2,'p_elementos','yacc.py',14),
  ('elementos -> elementos vids','elementos',2,'p_elementos','yacc.py',15),
  ('elementos -> <empty>','elementos',0,'p_elementos','yacc.py',16),
  ('elemento -> ELEMENTO NUMERO texto tipo area','elemento',5,'p_elemento','yacc.py',26),
  ('tipo -> TIPO texto','tipo',2,'p_tipo','yacc.py',34),
  ('tipo -> <empty>','tipo',0,'p_tipo','yacc.py',35),
  ('area -> AREA texto sin','area',3,'p_area','yacc.py',41),
  ('area -> AREA texto var','area',3,'p_area','yacc.py',42),
  ('area -> AREA texto lingua','area',3,'p_area','yacc.py',43),
  ('lingua -> LINGUA texto lingua','lingua',3,'p_lingua','yacc.py',50),
  ('lingua -> LINGUA texto nota','lingua',3,'p_lingua','yacc.py',51),
  ('lingua -> LINGUA texto vids','lingua',3,'p_lingua','yacc.py',52),
  ('lingua -> LINGUA texto','lingua',2,'p_lingua','yacc.py',53),
  ('sin -> SIN texto lingua','sin',3,'p_sin','yacc.py',62),
  ('sin -> SIN texto var','sin',3,'p_sin','yacc.py',63),
  ('vids -> vid','vids',1,'p_vids','yacc.py',69),
  ('vid -> VID texto » texto','vid',4,'p_vid','yacc.py',76),
  ('vid -> VID texto » texto vid','vid',5,'p_vid','yacc.py',77),
  ('var -> VAR texto lingua','var',3,'p_var','yacc.py',86),
  ('nota -> NOTA texto vids','nota',3,'p_nota','yacc.py',92),
  ('nota -> NOTA texto','nota',2,'p_nota','yacc.py',93),
  ('texto -> TEXTO texto','texto',2,'p_texto','yacc.py',102),
  ('texto -> NUMERO texto','texto',2,'p_texto','yacc.py',103),
  ('texto -> TEXTO','texto',1,'p_texto','yacc.py',104),
]
